export default {
  '1': {
    id: '1',
    name: '16lb bag of Skittles',
    imageUrl: '/static/skittles.jpg',
    price: 16.0,
    isTaxed: false,
    isImported: false,
  },
  '2': {
    id: '2',
    name: 'Walkman',
    imageUrl: '/static/walkman.jpg',
    price: 99.99,
    isTaxed: true,
    isImported: false,
  },
  '3': {
    id: '3',
    name: 'Bag of microwave Popcorn',
    imageUrl: '/static/popcorn.jpg',
    price: 0.99,
    isTaxed: false,
    isImported: false,
  },
  '4': {
    id: '4',
    name: 'Imported bag of Vanilla-Hazelnut Coffee',
    imageUrl: '/static/coffee.jpg',
    price: 11.0,
    isTaxed: false,
    isImported: true,
  },
  '5': {
    id: '5',
    name: 'Imported Vespa',
    imageUrl: '/static/vespa.jpg',
    price: 15001.25,
    isTaxed: true,
    isImported: true,
  },
  '6': {
    id: '6',
    name: 'Imported crate of Almond Snickers',
    imageUrl: '/static/snickers.jpg',
    price: 75.99,
    isTaxed: false,
    isImported: true,
  },
  '7': {
    id: '7',
    name: 'Discman',
    imageUrl: '/static/discman.jpg',
    price: 55.0,
    isTaxed: true,
    isImported: false,
  },
  '8': {
    id: '8',
    name: 'Imported Bottle of Wine',
    imageUrl: '/static/wine.jpg',
    price: 10.0,
    isTaxed: true,
    isImported: true,
  },
  '9': {
    id: '9',
    name: '300# bag of Fair-Trade Coffee',
    imageUrl: '/static/coffee.jpg',
    price: 997.99,
    isTaxed: false,
    isImported: false,
  },
};
